### ISSUE TITLE
select nodes only when certain props are present

### ISSUE THREAD

**Issue by gitfy** [lloyd/JSONSelectTests#3]
Hi,
I am looking to find out how to write the select, if i want to match all the nodes where a certain set of attributes are present. Like for example, 

:root > :has(string.type) && :has(string.key)

like above, but the above query return even if any one of the property is not present. I want the result set to contain only if both the properties are defined. Is this possible ?

Thanks.

**Comment by lloyd** [comment]
try `:root > :has(strying.type):has(string.key)`

On the demo site here: http://jsonselect.org/#tryit  You can test the following query which is similar:

```
.languagesSpoken :has(.lang):has(.level)
```

**Comment by gitfy** [comment]
thanks
